source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'LeakFinder_Example', :exclusive => true do
  pod "LeakFinder", :path => "../"
end

target 'LeakFinder_Tests', :exclusive => true do
  pod "LeakFinder", :path => "../"

  pod 'Kiwi'
end
